### ISSUE TITLE
Must be reloaded after opening first window in order to work

### ISSUE THREAD

**Issue by NCLI** [rholder/i3status-title-on-bar#1]
What happens: 

1. i3 is started, with no open windows or DE.
2. The i3status command does not give any output to i3, and eventually crashes with an error.
3. I open a window, and press shift+super+r to reload i3.
4. i3status works correctly, including window title.
5. The window is closed, and the title disappears from the i3bar, but i3status continues to work.

What I expect to happen:
1. i3 is started, with no open windows or DE.
2. The i3status command works correctly, displaying no windows title until one is opened.

**Comment by bowbored** [comment]
I have the same bug. I made an improvised fix that runs on startup.
It runs automatically this command: "urxvt -e i3-msg restart", which will open a Terminal and refresh i3 and then close it again.
I used a bash script but you can probably just write it into the i3 config.

**Comment by AlexNaga** [comment]
Based on the comment above, I was able to put this into the i3 config: `exec --no-startup-id "sleep 20; urxvt -e i3-msg restart"`

**Comment by rholder** [comment]
I was finally able to reproduce this issue locally on a new Debian 12 installation. We're getting tripped up [here](https://github.com/BurntSushi/xgb/blob/deaf085860bc2ec870e50cacc83c467b3501a404/help.go#L87), since there's no check that the byte slice is at least 4 bytes which was causing a `panic`:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/BurntSushi/xgb.Get32(...)
        /home/runner/go/pkg/mod/github.com/!burnt!sushi/xgb@v0.0.0-20160522181843-27f122750802/help.go:87
github.com/rholder/i3status-title-on-bar/pkg/window.X11.activeWindow(...)
        /home/runner/work/i3status-title-on-bar/i3status-title-on-bar/pkg/window/x11.go:97
github.com/rholder/i3status-title-on-bar/pkg/window.X11.ActiveWindowTitle(...)
        /home/runner/work/i3status-title-on-bar/i3status-title-on-bar/pkg/window/x11.go:126
github.com/rholder/i3status-title-on-bar/pkg/i3.RunJSONParsingLoop(...)
        /home/runner/work/i3status-title-on-bar/i3status-title-on-bar/pkg/i3/i3.go:109
main.main()
        /home/runner/work/i3status-title-on-bar/i3status-title-on-bar/cmd/i3status-title-on-bar/main.go:159
```

I've added a more [specific check](https://github.com/rholder/i3status-title-on-bar/commit/75b3b82330a87e03acd99a95be79087ef3089f4b) to handle all cases where the `Value` is not exactly 4 bytes which should now cover the 0 byte situation we've been seeing. This change appears to have cleared it up locally for me. Thanks to everyone here that took the time to contribute their observations and workarounds. This update is in the [latest release](https://github.com/rholder/i3status-title-on-bar/releases/tag/v0.6.3).
